### ISSUE TITLE
存储增加CheckPoint机制

### ISSUE THREAD

**Issue by liyue2008** [chubaostream/joyqueue#37]
## 现状

由于消息的索引是异步创建异步刷盘，所以重启后，需要扫描消息文件，恢复索引。当前对于PG索引的恢复策略是：找到每个partition的最后一条索引对应的消息尾部的位置（消息全局位置 + 消息长度），取这些位置的最小值，可以保证，这个位置之前的所有消息都有索引，这个位置之后的消息有可能有索引，有可能没有，这个位置成为**安全索引位置**。所以，目前的策略是，启动后，从安全索引位置开始，重建所有消息的索引。

## 问题

目前遇到的问题是，在指定分区发送消息，并且数据严重倾斜的情况下，Broker重启后，可能需要较长的时间恢复索引。极端情况下，需要重建全部索引，耗时较长。比如，一个PG有n个partition，如果其中一个partition一条消息都没有写入过，重启时，这个安全索引位置为0，需要重建全部索引。

## 解决方案

存储层，每个PG增加一个CheckPoint文件，定期记录当前的安全索引位置。重启时，首先读取CheckPoint中的安全索引位置，从这个位置来恢复索引。如果CheckPoint文件不存在或者读取失败，继续按照现有策略恢复索引。

CheckPoint文件位于PG目录下，文件名固定为`checkpoint`。文件采用JSON格式，目的是为了便于修改。例子：

```json
{
  "Version": 0,
  "IndexPosition": 88888, 
  "partitions": [
    {"partition": 0, "index": 666},
    {"partition": 1, "index": 333},
    {"partition": 2, "index": 22}
  ]
}
```

其中Version为CheckPoint文件的版本号，目前固定为0，后续修改文件格式后顺序递增版本号。IndexPosition属性记录安全索引位置。partitions 记录当前每个分区的下一条索引序号。

## 需要做的修改

1. 更新属性：PartitionGroupStoreManager#indexPosition
    1. 索引刷盘之后：需要同步或异步更新indexPosition
    1. 回滚的时候：回滚的时候需要同步回滚indexPosition

2. PartitionGroupStoreManager中启动一个定时器，定时写入CheckPoint文件，默认的周期是60S。
3. 修改PartitionGroupStoreManager#recoverPartitions恢复索引逻辑，优先读取CheckPoint文件，以CheckPoint文件中记录的IndexPosition为准返回安全索引位置。
4. 修改PartitionGroupStoreManager#stop方法，在停止刷盘线程和写入CheckPoint定时器之后，再执行一次写入CheckPoint。
5. 恢复PartitionGroup时，PartitionGroupStoreManager#recoverIndices方法中，增加如下逻辑：
    1. 读取checkpoint文件，检查每个分区的下一条索引序号是否大于等于checkpoint中记录的索引序号；
    2. 如果是，使用checkpoint中记录的indexPosition继续恢复索引；
    3. 否则，使用目前的逻辑计算出的indexPosition继续恢复索引。

## 讨论

~~由于目前采用异步刷盘，并且不会调用force强制刷盘，极端情况下（比如服务器掉电或者磁盘满），已刷盘的数据也不能保证一定安全写入到磁盘中。如何保证CheckPoint中记录的安全刷盘位置之前的索引数据一定安全的写入到磁盘中了呢？~~

**Comment by nera0** [comment]
是否可以将checkpoint所对应的索引位置记录一下，恢复时check该索引位置是否存在，如果存在则从checkpoint开始恢复，如果不存在则按原有策略恢复

**Comment by liyue2008** [comment]
考虑增加一个机制，每写完一个文件之后，调用一下force刷盘。

**Comment by liyue2008** [comment]
Fixed in 4.2.0
