### ISSUE TITLE
请问相比kafka的优势在哪里

### ISSUE THREAD

**Issue by XLPE** [chubaostream/joyqueue#7]
基于文档中描述，分布式协议是raft实现，请教一下相比kafka的核心优势在哪里？是否还保留kafka分区的概念，集群的线性扩容能否提高吞吐，是如何做到的呢？

**Comment by liyue2008** [comment]
JoyQueue可以兼容Kafka的客户端，所以在使用层面，和Kafka的所有概念都是完全兼容的，包括分区这个概念，功能也完全兼容。

但是在实现方式上和Kafka相比有很大的区别，我们会陆续更新设计相关的文档来说明设计和实现的原理。

JoyQueue最主要的2个优势是高性能和多协议支持，关于性能可以参照[性能测试](https://github.com/joyqueue/joyqueue/blob/master/docs/cn/performance.md)，同样场景下，我们测得JoyQueue的性能非常明显优于Kafka，为了避免争议，我们只公布了JoyQueue的测试结果。感兴趣的同学可以自己做一个简单的测试来验证一下。

集群也可以支持通过线性扩容来提升总体的吞吐量，配置也很简单，在JoyQueue Web中给主题增加分区组就可以了。这和Kafka增加分区来扩容是类似的。
